#!/usr/bin/python
# -*- coding: utf-8 -*-

# 是否启动插件
IS_START = True

# 是否启动url重复验证
# True 开启验证, False 关闭验证
URL_REPEATED_VERIFY = True

# 是否启动Proxy模块请求转发
IS_START_PROXY_FORWARD_REQUESTS = True

# 是否启动Repeater模块请求转发
IS_START_REPEATER_FORWARD_REQUESTS = False

# 允许请求转发的列表
IS_GET_FORWARD_REQUESTS = True
IS_POST_FORWARD_REQUESTS = True
IS_PUT_FORWARD_REQUESTS = True
IS_PATCH_FORWARD_REQUESTS = True
IS_DELETE_FORWARD_REQUESTS = True
IS_COPY_FORWARD_REQUESTS = True
IS_HEAD_FORWARD_REQUESTS = True
IS_OPTIONS_FORWARD_REQUESTS = False
IS_LINK_FORWARD_REQUESTS = True
IS_UNLINK_FORWARD_REQUESTS = True
IS_PURGE_FORWARD_REQUESTS = True
IS_LOCK_FORWARD_REQUESTS = True
IS_UNLOCK_FORWARD_REQUESTS = True
IS_PROPFIND_FORWARD_REQUESTS = True
IS_VIEW_FORWARD_REQUESTS = True